title: David Berberena's Data Science Portfolio
description: Past and current projects come together to highlight the skills acquired to make an impact in the data science community.
theme: jekyll-theme-cayman
